### ISSUE TITLE
Add online friends placeholder

### ISSUE THREAD

**Issue by ChefMC** [Simonsator/Party-and-Friends-Spigot-MySQL-API#4]
Not so important to know how much friends you have added. That count can be also rarely change. But it's very informative and useful to know how much your friends are online now.

And use this placeholder also in server list MOTD (to don't join server just for checking online friends count)

**Comment by Simonsator** [comment]
This will probably be added in a future release. There is already a suggestion for that on the discord. To keep track of the implementation of this feature, please take a look at the suggestion channel on the discord.
